bind_addr = ":8080"
log_level = "debug"
database_url = "user=postgres host=localhost dbname=restapi_dev sslmode=disable"
session_key = "879871247sdf0jndvmsnl12412bhv46723i08sufsjkdnfjkbqrbeby3g413gbghasd"